const fs = require('fs');
const path = require('path');

const dirs = [
  'apps/api-gateway/src',
  'apps/auth-service/src/application/services',
  'apps/auth-service/src/domain/entities',
  'apps/auth-service/src/domain/repositories',
  'apps/auth-service/src/infrastructure/controllers',
  'apps/auth-service/src/infrastructure/database',
  'apps/auth-service/src/infrastructure/routes',
  'apps/auth-service/src/interfaces',
  'apps/auth-service/src/config',
  'apps/auth-service/tests',
  'apps/user-service/src/application',
  'apps/user-service/src/domain',
  'apps/user-service/src/infrastructure',
  'apps/user-service/src/interfaces',
  'apps/user-service/src/config',
  'apps/user-service/tests',
  'apps/wallet-service/src/application',
  'apps/wallet-service/src/domain',
  'apps/wallet-service/src/infrastructure',
  'apps/wallet-service/src/interfaces',
  'apps/wallet-service/src/config',
  'apps/wallet-service/tests',
  'apps/payment-service/cmd/api',
  'apps/payment-service/internal/application',
  'apps/payment-service/internal/domain/entities',
  'apps/payment-service/internal/domain/repositories',
  'apps/payment-service/internal/infrastructure/db',
  'apps/payment-service/internal/infrastructure/kafka',
  'apps/payment-service/internal/interfaces/http',
  'apps/payment-service/pkg',
  'apps/notification-service/src/application',
  'apps/notification-service/src/domain',
  'apps/notification-service/src/infrastructure',
  'apps/notification-service/src/interfaces',
  'apps/notification-service/src/config',
  'apps/notification-service/tests',
  'apps/fraud-detection-service/src/application',
  'apps/fraud-detection-service/src/domain',
  'apps/fraud-detection-service/src/infrastructure',
  'apps/fraud-detection-service/src/interfaces',
  'apps/fraud-detection-service/src/config',
  'apps/fraud-detection-service/tests',
  'apps/transaction-history-service/src/application',
  'apps/transaction-history-service/src/domain',
  'apps/transaction-history-service/src/infrastructure',
  'apps/transaction-history-service/src/interfaces',
  'apps/transaction-history-service/src/config',
  'apps/transaction-history-service/tests',
  'packages/shared-types/src',
  'packages/event-contracts/src',
  'packages/logger/src',
  'packages/db-prisma/prisma',
  'packages/db-prisma/src',
  'scripts',
  'k8s/base',
];

dirs.forEach(dir => {
  fs.mkdirSync(path.join(__dirname, dir), { recursive: true });
});

console.log('Directories created successfully.');
