apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-gateway-manifests.yaml
- auth-service-manifests.yaml
- fraud-detection-service-manifests.yaml
- frontend-manifests.yaml
- notification-service-manifests.yaml
- payment-service-manifests.yaml
- postgres-manifests.yaml
- transaction-history-service-manifests.yaml
- user-service-manifests.yaml
- wallet-service-manifests.yaml

images:
- name: payflow/api-gateway
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/api-gateway
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/auth-service
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/auth-service
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/fraud-detection-service
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/fraud-detection-service
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/frontend
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/frontend
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/notification-service
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/notification-service
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/payment-service
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/payment-service
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/transaction-history-service
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/transaction-history-service
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/user-service
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/user-service
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
- name: payflow/wallet-service
  newName: 827566277132.dkr.ecr.us-east-1.amazonaws.com/payflow/wallet-service
  newTag: dfb8289515d99374913ef90cf2bca0b6b0b0b3ff
