apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payflow-system
  namespace: argocd   # ArgoCD must be installed in this namespace
spec:
  project: default
  source:
    # Correct GitHub repository URL
    repoURL: 'https://github.com/dollarsmoney/PayFlow-Cloud-MicroService-Kubernetes-.git'
    targetRevision: HEAD
    path: k8s           # The path to the folder containing all our microservice manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: payflow-system  # Where the microservices will actually be deployed
  syncPolicy:
    automated:
      prune: true       # Automatically delete resources that are removed from Git
      selfHeal: true    # Automatically revert manual changes made directly in the cluster
    syncOptions:
      - CreateNamespace=true  # ArgoCD will create the 'payflow-system' namespace if it doesn't exist
